/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transportationmanagementsystemgui;

import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Btrlp8
 */
public class CompanySubVehicleList extends javax.swing.JFrame {

    public DefaultListModel mod1;
    public int indextemp;

    /**
     * Creates new form CustomerSub2ChoosingTheVehicle
     */
    public CompanySubVehicleList() {

        // bir önceki sekmeden train ise
        javax.swing.ImageIcon bus1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\bus.png");
        javax.swing.ImageIcon train1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\train.png");
        javax.swing.ImageIcon plane1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\plane.png");
        mod1 = new DefaultListModel();

        for (Vehicle chosenVehicleElement : main.companyelementtemp1.getcompanies_vehicles()) {
            Object tempobject = chosenVehicleElement.getCompanyName() + "  " + chosenVehicleElement.getVehicleCode();
            mod1.addElement(tempobject);

        }
        if (mod1.isEmpty()) {
            Object tempobject1 = "No Vehicles";
            mod1.addElement(tempobject1);
        }
        initComponents();

        if (true) {
            jLabel1.setIcon(plane1);
            //SwingUtilities.updateComponentTreeUI(this);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JList<String> jList1 = new javax.swing.JList<>();
        seat2 = new javax.swing.JToggleButton();
        seat3 = new javax.swing.JToggleButton();
        seat5 = new javax.swing.JToggleButton();
        seat1 = new javax.swing.JToggleButton();
        seat4 = new javax.swing.JToggleButton();
        seat6 = new javax.swing.JToggleButton();
        seat7 = new javax.swing.JToggleButton();
        seat8 = new javax.swing.JToggleButton();
        seat9 = new javax.swing.JToggleButton();
        seat10 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullSeats = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destination = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vehicleID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        addVehicle = new javax.swing.JToggleButton();
        deleteThisVehicle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(858, 496));
        setResizable(false);
        setSize(new java.awt.Dimension(858, 496));
        getContentPane().setLayout(null);

        jList1.setModel(mod1);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(43, 44, 138, 259);

        seat2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        getContentPane().add(seat2);
        seat2.setBounds(620, 170, 70, 80);

        seat3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });
        getContentPane().add(seat3);
        seat3.setBounds(540, 80, 70, 80);

        seat5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        getContentPane().add(seat5);
        seat5.setBounds(460, 80, 70, 80);

        seat1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });
        getContentPane().add(seat1);
        seat1.setBounds(620, 80, 70, 80);

        seat4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });
        getContentPane().add(seat4);
        seat4.setBounds(540, 170, 70, 80);

        seat6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat6ActionPerformed(evt);
            }
        });
        getContentPane().add(seat6);
        seat6.setBounds(460, 170, 70, 80);

        seat7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat7ActionPerformed(evt);
            }
        });
        getContentPane().add(seat7);
        seat7.setBounds(380, 80, 70, 80);

        seat8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat8ActionPerformed(evt);
            }
        });
        getContentPane().add(seat8);
        seat8.setBounds(380, 170, 70, 80);

        seat9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat9ActionPerformed(evt);
            }
        });
        getContentPane().add(seat9);
        seat9.setBounds(300, 80, 70, 80);

        seat10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat10ActionPerformed(evt);
            }
        });
        getContentPane().add(seat10);
        seat10.setBounds(300, 170, 70, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\bus.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 90, 537, 136);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Full Seats  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 350, 80, 30);

        fullSeats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullSeats.setText("4");
        getContentPane().add(fullSeats);
        fullSeats.setBounds(360, 350, 40, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Destination :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 350, 100, 30);

        destination.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destination.setText("istanbul - ankara");
        getContentPane().add(destination);
        destination.setBounds(510, 350, 120, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 310, 80, 30);

        vehicleID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vehicleID.setText("11231");
        getContentPane().add(vehicleID);
        vehicleID.setBounds(360, 310, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 310, 43, 30);

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setText("19/03/2023");
        getContentPane().add(date);
        date.setBounds(510, 310, 120, 30);

        addVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addVehicle.setText("Add New Vehicle");
        addVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(addVehicle);
        addVehicle.setBounds(30, 330, 160, 30);

        deleteThisVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteThisVehicle.setText("Delete This Vehicle");
        deleteThisVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteThisVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(deleteThisVehicle);
        deleteThisVehicle.setBounds(260, 410, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        javax.swing.JList<String> theList = (javax.swing.JList<String>) evt.getSource();
        SwingUtilities.updateComponentTreeUI(this);
        if (evt.getClickCount() == 1) {
            int index = theList.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object o = theList.getModel().getElementAt(index);
                javax.swing.ImageIcon seatminiRED = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatminiRED.png");
                javax.swing.ImageIcon seatminiGREEN = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatminiGREEN.png");
                boolean flag;
                indextemp = index;
                int i = 0;
                for (Vehicle chosenVehicleElement : main.companyelementtemp1.getcompanies_vehicles()) {
                    if (i == index) {
                        flag = true;
                        //System.out.println("please choose number for seat from 1 to 10 : ");
                        //int chosenSeat1 = choosenseat;

                        //tempcustomer = chosenVehicleElement.getSeatStatus();
                        /*
                        for (int j = 0; j < tempcustomer.length; j++) {
                            if(chosenSeat1 == j && chosenSeat1 != null){
                                tempcustomer[j] 
                                SeatStatus.setText("");
                            }
                            
                        }
                         */
                        Customer[] fullseats = chosenVehicleElement.getSeatStatus();
                        int fullseatnumber = 0;
                        int m = 0;
                        for (Customer fullseat : fullseats) {
                            if (fullseat != null) {
                                fullseatnumber++;
                                if (m == 0) {
                                    seat1.setIcon(seatminiRED);
                                } else if (m == 1) {
                                    seat2.setIcon(seatminiRED);
                                } else if (m == 2) {
                                    seat3.setIcon(seatminiRED);
                                } else if (m == 3) {
                                    seat4.setIcon(seatminiRED);
                                } else if (m == 4) {
                                    seat5.setIcon(seatminiRED);
                                } else if (m == 5) {
                                    seat6.setIcon(seatminiRED);
                                } else if (m == 6) {
                                    seat7.setIcon(seatminiRED);
                                } else if (m == 7) {
                                    seat8.setIcon(seatminiRED);
                                } else if (m == 8) {
                                    seat9.setIcon(seatminiRED);
                                } else if (m == 9) {
                                    seat10.setIcon(seatminiRED);
                                }
                            } else {
                                if (m == 0) {
                                    seat1.setIcon(seatminiGREEN);
                                } else if (m == 1) {
                                    seat2.setIcon(seatminiGREEN);
                                } else if (m == 2) {
                                    seat3.setIcon(seatminiGREEN);
                                } else if (m == 3) {
                                    seat4.setIcon(seatminiGREEN);
                                } else if (m == 4) {
                                    seat5.setIcon(seatminiGREEN);
                                } else if (m == 5) {
                                    seat6.setIcon(seatminiGREEN);
                                } else if (m == 6) {
                                    seat7.setIcon(seatminiGREEN);
                                } else if (m == 7) {
                                    seat8.setIcon(seatminiGREEN);
                                } else if (m == 8) {
                                    seat9.setIcon(seatminiGREEN);
                                } else if (m == 9) {
                                    seat10.setIcon(seatminiGREEN);
                                }

                            }
                            m++;
                        }

                        String temp22 = (chosenVehicleElement.getRoute());
                        destination.setText(temp22);
                        String temp23 = (chosenVehicleElement.getVehicleCode());
                        vehicleID.setText(temp23);
                        /*
                        String temp24 = Integer.toString(chosenVehicleElement.getPrice());
                        seatPrice.setText(temp24);
                         */
                        String temp25 = (chosenVehicleElement.getDate());
                        date.setText(temp25);
                        String temp26 = Integer.toString(fullseatnumber);
                        fullSeats.setText(temp26);
                        SwingUtilities.updateComponentTreeUI(this);
                        break;

                    } else {
                        flag = false;
                    }
                    i++;
                }
                /*
            if(index == 1){
                seat1.setIcon(seatminiRED);
                seat3.setIcon(seatminiRED);
                SwingUtilities.updateComponentTreeUI(this);
                
                 
                
                
                
            }
            else{              
                seat1.setIcon(seatminiGREEN);
                seat3.setIcon(seatminiGREEN);
                SwingUtilities.updateComponentTreeUI(this);
            }
                 */

                System.out.println("Double-clicked on: " + o.toString());
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat4ActionPerformed

    private void seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat6ActionPerformed

    private void seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat7ActionPerformed

    private void seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat8ActionPerformed

    private void seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat9ActionPerformed

    private void seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat10ActionPerformed

    private void addVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);

        CompanySub2AddNewVehicle newframe4 = new CompanySub2AddNewVehicle();
        newframe4.setLocationRelativeTo(null);
        newframe4.setVisible(true);

        newframe4.toFront();
    }//GEN-LAST:event_addVehicleActionPerformed

    private void deleteThisVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteThisVehicleActionPerformed
        // TODO add your handling code here:
        
        int m = 0;
        for (Vehicle chosenVehicleForDelete : main.companyelementtemp1.getcompanies_vehicles()) {
             if (m == indextemp) {
                 
                 
                 main.companyelementtemp1.deleteVehicle(chosenVehicleForDelete, main.vehicle);
                 this.toBack();
                setVisible(false);
                this.dispose();
                CompanySubVehicleList tempframe1 = new CompanySubVehicleList();                        
                tempframe1.setState(java.awt.Frame.NORMAL);
                tempframe1.setLocationRelativeTo(null);
                tempframe1.setVisible(true);
                tempframe1.toFront();
                 break;
                 
             }
                    
            
            
            m++;
        }
        
        
        
        
    }//GEN-LAST:event_deleteThisVehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanySubVehicleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanySubVehicleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanySubVehicleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanySubVehicleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanySubVehicleList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addVehicle;
    private javax.swing.JLabel date;
    private javax.swing.JButton deleteThisVehicle;
    private javax.swing.JLabel destination;
    private javax.swing.JLabel fullSeats;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JToggleButton seat1;
    public javax.swing.JToggleButton seat10;
    public javax.swing.JToggleButton seat2;
    public javax.swing.JToggleButton seat3;
    public javax.swing.JToggleButton seat4;
    public javax.swing.JToggleButton seat5;
    public javax.swing.JToggleButton seat6;
    public javax.swing.JToggleButton seat7;
    public javax.swing.JToggleButton seat8;
    public javax.swing.JToggleButton seat9;
    private javax.swing.JLabel vehicleID;
    // End of variables declaration//GEN-END:variables
}
