/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transportationmanagementsystemgui;

/**
 *
 * @author Btrlp8
 */
public class CustomerSubReservation extends javax.swing.JFrame {

    public static String ticketPrice1;
    public static String companyName1;
    public static String vehicleType1;
    public static String seatNumber1;
    public static String date1;
    public static String route1;
    public static String vehicleCode1;

    /**
     * Creates new form CustomerSubReservation
     */
    public CustomerSubReservation() {
        boolean flg = false;
        for (Vehicle veh : main.vehicle) {
            if (main.customerelementtemp1.getVehicleNumber().equalsIgnoreCase(veh.getVehicleCode())) {
                for (Company element : main.company) {
                    if (element.getName().equalsIgnoreCase(veh.getCompanyName())) {
                        flg = true;
                        if (veh instanceof Bus) {
                            ticketPrice1 = Integer.toString(veh.getPrice());
                            companyName1 = veh.getCompanyName();
                            vehicleType1 = "Bus";
                            seatNumber1 = Integer.toString(main.customerelementtemp1.getChosenSeatNumber());
                            date1 = veh.getDate();
                            route1 = veh.getRoute();
                            vehicleCode1 = veh.getVehicleCode();

                        } else if (veh instanceof Plane) {
                            ticketPrice1 = Integer.toString(veh.getPrice());
                            companyName1 = veh.getCompanyName();
                            vehicleType1 = "Plane";
                            seatNumber1 = Integer.toString(main.customerelementtemp1.getChosenSeatNumber());
                            date1 = veh.getDate();
                            route1 = veh.getRoute();
                            vehicleCode1 = veh.getVehicleCode();

                        } else if (veh instanceof Train) {
                            /*
                            System.out.println("Name-> " + main.customerelementtemp1.getName() + " Surname-> " + main.customerelementtemp1.getSurname()
                                    + " Gender-> " + main.customerelementtemp1.getGender() + " Company-> " + veh.getCompanyName() + " Vehicle type Train-> " + " Vehicle code-> "
                                    + veh.getVehicleCode() + " Seat number-> " + main.customerelementtemp1.getChosenSeatNumber() + " Date-> " + veh.getDate() + " Route-> " + veh.getRoute() + " Ticket Price-> "
                                    + veh.getPrice() + " Baggage-> " + veh.getBaggageInformation() + " Entertainment System Statu-> " + element.getEntertainmentSystemStatus()
                                    + " internet Connection Status-> " + element.getInternetConnectionStatus() + " Meal Service-> " + element.getMealService());
                             */
                            ticketPrice1 = Integer.toString(veh.getPrice());
                            companyName1 = veh.getCompanyName();
                            vehicleType1 = "Train";
                            seatNumber1 = Integer.toString(main.customerelementtemp1.getChosenSeatNumber());
                            date1 = veh.getDate();
                            route1 = veh.getRoute();
                            vehicleCode1 = veh.getVehicleCode();

                        }
                    }
                }
            }
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        route = new javax.swing.JLabel();
        ticketPrice = new javax.swing.JLabel();
        companyName = new javax.swing.JLabel();
        vehicleType = new javax.swing.JLabel();
        seatNumber = new javax.swing.JLabel();
        vehicleCode = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 360));
        setSize(new java.awt.Dimension(550, 360));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ticket Price :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 50, 100, 32);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(391, 299, 101, 34);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Refund");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(288, 299, 91, 34);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Company name  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 117, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Vehicle Type  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 97, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Seat Number :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 96, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 39, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Route  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(65, 219, 51, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Vehicle Code  :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(250, 190, 99, 20);

        route.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        route.setText(route1);
        getContentPane().add(route);
        route.setBounds(130, 220, 80, 20);

        ticketPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ticketPrice.setText(ticketPrice1);
        getContentPane().add(ticketPrice);
        ticketPrice.setBounds(170, 50, 100, 32);

        companyName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        companyName.setText(companyName1);
        getContentPane().add(companyName);
        companyName.setBounds(190, 92, 100, 20);

        vehicleType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vehicleType.setText(vehicleType1);
        getContentPane().add(vehicleType);
        vehicleType.setBounds(180, 122, 100, 20);

        seatNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seatNumber.setText(seatNumber1);
        getContentPane().add(seatNumber);
        seatNumber.setBounds(180, 160, 100, 20);

        vehicleCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vehicleCode.setText(vehicleCode1);
        getContentPane().add(vehicleCode);
        vehicleCode.setBounds(370, 190, 100, 20);

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setText(date1);
        getContentPane().add(date);
        date.setBounds(120, 190, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new CustomerSubDateAndDestination().toFront();
        new CustomerSubDateAndDestination().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (Vehicle veh : main.vehicle) {
            if (main.customerelementtemp1.getVehicleNumber().equalsIgnoreCase(veh.getVehicleCode())) {                
                veh.refund(main.customerelementtemp1);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSubReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSubReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSubReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSubReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSubReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel route;
    private javax.swing.JLabel seatNumber;
    private javax.swing.JLabel ticketPrice;
    private javax.swing.JLabel vehicleCode;
    private javax.swing.JLabel vehicleType;
    // End of variables declaration//GEN-END:variables
}
