/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transportationmanagementsystemgui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Btrlp8
 */
public class CustomerSub2ChoosingTheVehicle extends javax.swing.JFrame {
    public List<Vehicle> chosen_vehiclesTEMP;
    public DefaultListModel mod1;
    public int choosenseat;
    public int chosenVehicleNumberGlobal;
    public Customer[] tempcustomer;
    /**
     * Creates new form CustomerSub2ChoosingTheVehicle
     */
    public CustomerSub2ChoosingTheVehicle(List<Vehicle> chosen_vehicles) {
        chosen_vehiclesTEMP = new ArrayList<Vehicle>();
        chosen_vehiclesTEMP = chosen_vehicles;
        mod1 = new DefaultListModel();
        choosenseat=-1;
        chosenVehicleNumberGlobal=-1;
        for (Vehicle chosenVehicleElement : chosen_vehiclesTEMP) {
                Object tempobject = chosenVehicleElement.getCompanyName() + "  " + chosenVehicleElement.getVehicleCode() + "  " + chosenVehicleElement.getPrice();
                mod1.addElement(tempobject);
                
            }
        
        initComponents();
        // bir önceki sekmeden train ise
        javax.swing.ImageIcon bus1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\bus.png");
        javax.swing.ImageIcon train1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\train.png");
        javax.swing.ImageIcon plane1 = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\plane.png");
             
        
        if(true){
            jLabel1.setIcon(plane1);
            //SwingUtilities.updateComponentTreeUI(this);
                
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JList<String> jList1 = new javax.swing.JList<>();
        seat2 = new javax.swing.JToggleButton();
        seat3 = new javax.swing.JToggleButton();
        seat5 = new javax.swing.JToggleButton();
        seat1 = new javax.swing.JToggleButton();
        seat4 = new javax.swing.JToggleButton();
        seat6 = new javax.swing.JToggleButton();
        seat7 = new javax.swing.JToggleButton();
        seat8 = new javax.swing.JToggleButton();
        seat9 = new javax.swing.JToggleButton();
        seat10 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SeatStatus = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JLabel();
        seatPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        baggageInfo = new javax.swing.JLabel();
        jButtonBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(858, 496));
        setResizable(false);
        setSize(new java.awt.Dimension(858, 496));
        getContentPane().setLayout(null);

        jList1.setModel(mod1);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(43, 44, 138, 259);

        seat2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat2ActionPerformed(evt);
            }
        });
        getContentPane().add(seat2);
        seat2.setBounds(620, 170, 70, 80);

        seat3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });
        getContentPane().add(seat3);
        seat3.setBounds(540, 80, 70, 80);

        seat5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat5ActionPerformed(evt);
            }
        });
        getContentPane().add(seat5);
        seat5.setBounds(460, 80, 70, 80);

        seat1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });
        getContentPane().add(seat1);
        seat1.setBounds(620, 80, 70, 80);

        seat4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });
        getContentPane().add(seat4);
        seat4.setBounds(540, 170, 70, 80);

        seat6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat6ActionPerformed(evt);
            }
        });
        getContentPane().add(seat6);
        seat6.setBounds(460, 170, 70, 80);

        seat7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat7ActionPerformed(evt);
            }
        });
        getContentPane().add(seat7);
        seat7.setBounds(380, 80, 70, 80);

        seat8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat8ActionPerformed(evt);
            }
        });
        getContentPane().add(seat8);
        seat8.setBounds(380, 170, 70, 80);

        seat9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat9ActionPerformed(evt);
            }
        });
        getContentPane().add(seat9);
        seat9.setBounds(300, 80, 70, 80);

        seat10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatmini.png")); // NOI18N
        seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat10ActionPerformed(evt);
            }
        });
        getContentPane().add(seat10);
        seat10.setBounds(300, 170, 70, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\bus.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 90, 537, 136);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Balance:  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 20, 70, 30);

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("aa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 20, 70, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Seat Status   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 300, 90, 30);

        SeatStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SeatStatus.setText("Empty");
        getContentPane().add(SeatStatus);
        SeatStatus.setBounds(380, 300, 90, 30);

        jFrame5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jFrame5.setText("Price  :");
        getContentPane().add(jFrame5);
        jFrame5.setBounds(510, 300, 60, 30);

        seatPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seatPrice.setText("100");
        getContentPane().add(seatPrice);
        seatPrice.setBounds(570, 300, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Baggage İnfo  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 350, 110, 20);

        baggageInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        baggageInfo.setText("100");
        getContentPane().add(baggageInfo);
        baggageInfo.setBounds(380, 350, 60, 20);

        jButtonBuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBuy.setText("Buy selected Seat");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuy);
        jButtonBuy.setBounds(340, 400, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
        // TODO add your handling code here:
        choosenseat = 2;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
        // TODO add your handling code here:
        choosenseat = 0;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
        
    }//GEN-LAST:event_seat1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        javax.swing.JList<String> theList = (javax.swing.JList<String>)evt.getSource();
        if (evt.getClickCount() == 1) {
          int index = theList.locationToIndex(evt.getPoint());
          if (index >= 0) {
            Object o = theList.getModel().getElementAt(index);
            javax.swing.ImageIcon seatminiRED = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatminiRED.png");
            javax.swing.ImageIcon seatminiGREEN = new javax.swing.ImageIcon("C:\\Users\\Btrlp8\\Documents\\NetBeansProjects\\TransportationManagementSystemGUI\\images\\seatminiGREEN.png");
            
            chosenVehicleNumberGlobal = index;
            
            int chosenVehicleNumber = chosenVehicleNumberGlobal ;
            int i = 0;
            boolean flag = false;
            
                
            for (Vehicle chosenVehicleElement : chosen_vehiclesTEMP) {
                if (i == chosenVehicleNumber) {
                    flag = true;
                    //System.out.println("please choose number for seat from 1 to 10 : ");
                    //int chosenSeat1 = choosenseat;
                   
                        
                        tempcustomer = chosenVehicleElement.getSeatStatus();
                        /*
                        for (int j = 0; j < tempcustomer.length; j++) {
                            if(chosenSeat1 == j && chosenSeat1 != null){
                                tempcustomer[j] 
                                SeatStatus.setText("");
                            }
                            
                        }
 */
                       
                        String temp22 = Integer.toString(chosenVehicleElement.getBaggageInformation());
                        baggageInfo.setText(temp22);
                        String temp24 = Integer.toString(chosenVehicleElement.getPrice());
                        seatPrice.setText(temp24);
                        SwingUtilities.updateComponentTreeUI(this);
                        break;

                    
                } else {
                    flag = false;
                }
                i++;
            }
            /*
            // seat icon renklendirme 
            if(index == 0){
                seat1.setIcon(seatminiRED);
                seat3.setIcon(seatminiRED);
                SwingUtilities.updateComponentTreeUI(this);
                
                // eski hatalı yeni frame acıp kapıyordum
                this.toBack();
                setVisible(false);
                
                CustomerSub2ChoosingTheVehicle temp1 = new CustomerSub2ChoosingTheVehicle();
                temp1.seat1.setIcon(seatminiRED);
                temp1.seat3.setIcon(seatminiRED);
                temp1.setLocationRelativeTo(null);
                temp1.toFront();
                temp1.setVisible(true);
                temp1.setState(java.awt.Frame.NORMAL);
                ////////
                
                
            }
            else if(index == 1){
                
            }
            else{              
                seat1.setIcon(seatminiGREEN);
                seat3.setIcon(seatminiGREEN);
                SwingUtilities.updateComponentTreeUI(this);
            }
            */
            
            
            
            //System.out.println("Double-clicked on: " + o.toString());
          }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        // TODO add your handling code here:
        choosenseat = 3;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat4ActionPerformed

    private void seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat6ActionPerformed
        // TODO add your handling code here:
        choosenseat = 5;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat6ActionPerformed

    private void seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat7ActionPerformed
        // TODO add your handling code here:
        choosenseat = 6;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat7ActionPerformed

    private void seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat8ActionPerformed
        // TODO add your handling code here:
        choosenseat = 7;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat8ActionPerformed

    private void seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat9ActionPerformed
        // TODO add your handling code here:
        choosenseat = 8;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat9ActionPerformed

    private void seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat10ActionPerformed
        // TODO add your handling code here:
        choosenseat = 9;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat10ActionPerformed

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        // TODO add your handling code here:
        //System.out.println("please choose number for  vehicle from 1 to " + chosen_vehicles.size() + " : ");
        
            int chosenVehicleNumber = chosenVehicleNumberGlobal ;
            int i = 0;
            boolean flag = false;
            
                
            for (Vehicle chosenVehicleElement : chosen_vehiclesTEMP) {
                if (i == chosenVehicleNumber) {
                    flag = true;
                    //System.out.println("please choose number for seat from 1 to 10 : ");
                    int chosenSeat1 = choosenseat;
                    if (chosenVehicleElement.addCustomer(LoginCustomer.customerelementtemp, chosenSeat1)) {
                        LoginCustomer.customerelementtemp.setVehicleNumber(chosenVehicleElement.getVehicleCode());
                        LoginCustomer.customerelementtemp.setBaggageInformation(chosenVehicleElement.getBaggageInformation());
                        LoginCustomer.customerelementtemp.setChosenSeatNumber(chosenSeat1);
                        break;

                    }
                } else {
                    flag = false;
                }
                i++;
            }
            
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat2ActionPerformed
        // TODO add your handling code here:
        choosenseat = 1;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat2ActionPerformed

    private void seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat5ActionPerformed
        // TODO add your handling code here:
        choosenseat = 4;
        if(tempcustomer[choosenseat] != null){
            SeatStatus.setText("Full");
        }
        else{
            SeatStatus.setText("Empty");
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_seat5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSub2ChoosingTheVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSub2ChoosingTheVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSub2ChoosingTheVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSub2ChoosingTheVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSub2ChoosingTheVehicle(CustomerSubDateAndDestination.chosen_vehicles).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SeatStatus;
    private javax.swing.JLabel baggageInfo;
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JLabel jFrame5;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JToggleButton seat1;
    public javax.swing.JToggleButton seat10;
    public javax.swing.JToggleButton seat2;
    public javax.swing.JToggleButton seat3;
    public javax.swing.JToggleButton seat4;
    public javax.swing.JToggleButton seat5;
    public javax.swing.JToggleButton seat6;
    public javax.swing.JToggleButton seat7;
    public javax.swing.JToggleButton seat8;
    public javax.swing.JToggleButton seat9;
    private javax.swing.JLabel seatPrice;
    // End of variables declaration//GEN-END:variables
}
